#ifndef SETTINGSIDS_H
#define SETTINGSIDS_H
#define IDC_PREFS_TOGGLE_WINREMEMBER 500
#define IDC_PREFS_TOGGLE_bSplashScreen 501
#define IDC_PREFS_TOGGLE_SHOWFILEINTITLE 502
#define IDC_PREFS_EDIT_DEFAULT_PATH 503
#define IDC_PREFS_TOGGLE_EXIT_NORMAL_CONFIRM 504
#define IDC_PREFS_TOGGLE_EXIT_NOTSAVED_CONFIRM 505
#define IDC_PREFS_COMBO_DEFAULT_FONT 505
#define IDC_PREFS_TOGGLE_TOOLBAR 506
#define IDC_PREFS_TOGGLE_FONT_SIZE 507
#define IDC_PREFS_TOGGLE_DEFAULT_ZOOM 508
#define IDC_PREFS_TOGGLE_FULL_PATH 509
#define IDC_OK_BUTTON 510
#define IDC_CANCEL_BUTTON 511
#define IDC_PREFS_TOGGLE_TOOLBAR_TEXT 512
#define IDC_PREFS_TOGGLE_LINKS 513

#define IDC_PREFS_PLCHOLD_USA 514
#define IDC_PREFS_PLCHOLD_RU 515
#define IDC_PREFS_PLCHOLD_JP 516
#define IDC_PREFS_TABAREA 517
#define IDc_TOGGLE_LAST_SESSION 518
#define IDC_STARTUP_GROUPBOX 519
#define IDC_SHUTDOWN_GROUPBOX 520
#define IDC_TOOLBAR_GROUPBOX 521
#define IDC_STATBAR_GROUPBOX 522
#define IDC_MISC_GROUPBOX 523
#define IDC_RECENTS_GROUPBOX 524
#define IDC_PREFS_TOGGLE_RECENT_DUPS 525
#define IDC_EDITOR_GROUPBOX 526
#define IDC_PREFS_TOGGLE_RECENT_SHORT 527
#define IDC_PREFS_TOGGLE_STATUS_CURR_LINE_NUM 528
#define IDC_PREFS_TOGGLE_STATUS_ZOOM 529
#define IDC_PREFS_TOGGLE_STATUS_TEXT_LEN 530
#define IDC_STATUS_GROUPBOX 531
#define IDC_END 600 
#endif
